# Generated by Django 5.2.6 on 2025-09-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('mobile_num', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'organizers',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.JSONField(default=list)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=3, help_text='Duration in minutes')),
                ('type', models.CharField(choices=[('Normal', 'normal'), ('Reverse', 'reverse'), ('Jumble-Word', 'jumble-word')], max_length=15)),
                ('paragraphs', models.JSONField(default=list)),
                ('expired', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('ended', 'Ended')], default='waiting', max_length=10)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='typing_game.organizer')),
                ('participants', models.ManyToManyField(related_name='competitions', to='typing_game.participant')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('time_taken', models.FloatField(default=0.0)),
                ('total_keystrokes', models.IntegerField(default=0)),
                ('correct_keystrokes', models.IntegerField(default=0)),
                ('num_correct', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0.0, editable=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='typing_game.competition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_results', to='typing_game.participant')),
            ],
            options={
                'db_table': 'competition_results',
                'unique_together': {('competition', 'participant')},
            },
        ),
    ]
