# Generated by Django 5.2.6 on 2025-09-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('mobile_num', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'organizers',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('created_At', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'participants',
            },
        ),
    ]
