# Generated by Django 5.2.6 on 2025-09-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('mobile_num', models.BigIntegerField(max_length=10)),
                ('role', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
