# Generated by Django 5.2.6 on 2025-09-09 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='typing_game.organizer')),
                ('participants', models.ManyToManyField(blank=True, related_name='competitions', to='typing_game.participant')),
            ],
        ),
    ]
