# Generated by Django 5.2.6 on 2025-09-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Reverse', 'Reverse'), ('Jumble-words', 'Jumble-words')], max_length=15),
        ),
    ]
