# Generated by Django 5.2.6 on 2025-09-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='score',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
