# Generated by Django 5.2.6 on 2025-09-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_game', '0002_competitionresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='num_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.JSONField(default=list),
        ),
    ]
