# Generated by Django 5.2.6 on 2025-09-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_game', '0002_alter_participant_password_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='paragraphs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='competition',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('Normal', 'normal'), ('Reverse', 'reverse'), ('Jumble-Word', 'jumble-Word')], default=None, max_length=15),
        ),
    ]
