# Generated by Django 5.2.6 on 2025-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_game', '0003_competition_expired_competition_paragraphs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='end_time',
        ),
        migrations.AddField(
            model_name='competition',
            name='duration',
            field=models.IntegerField(default=3, help_text='Duration in minutes'),
        ),
    ]
