# Generated by Django 5.2.6 on 2025-09-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_game', '0004_remove_competition_end_time_competition_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('time_taken', models.FloatField(default=0.0)),
                ('total_keystrokes', models.IntegerField(default=0)),
                ('correct_keystrokes', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='typing_game.competition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_results', to='typing_game.participant')),
            ],
            options={
                'db_table': 'competition_results',
                'unique_together': {('competition', 'participant')},
            },
        ),
    ]
